### ISSUE TITLE
Add option to enable/disable recource pack

### ISSUE THREAD

**Issue by ErythroCraft** [CraftoryStudios/Craftory-Tech#132]
Hi,

can you give an update to enable/disable your resource pack?

I'm using more plugins with custom resource packs on my.
Now I must create a full pack for my server, to edit dublications.

All other plugins I installed on my server, have got an option like this.

**e.g. by QualitiArmory:**

> useDefaultResourcepack: false
> DefaultResourcepack: https://www.dropbox.com/s/cnh7mjc88mqprjd/QualityArmoryV2.1.8.zip?dl=1

**Comment by brettsaunders21** [comment]
There is already an option to disable the resource pack and host it yourself.

In the config.yml in the plugins folder set resourcePack.forcePack to false. You can then combined the resource pack with others and host yourself.

I'll look at changing the option name in future to make it clearer

**Comment by brettsaunders21** [comment]
Resource pack can be found here https://github.com/CraftoryStudios/Craftory-TechResources/releases/tag/V0.2.10
