### ISSUE TITLE
[BUG] Resource pack mistaking vanilla mushroom stem blocks as craftory blocks

### ISSUE THREAD

**Issue by cloakfox** [CraftoryStudios/Craftory-Tech#153]
I have been watching this project for a while now and wanted to try it out on a new setup, after installing Craftory 0.6.0 & latest resourcepack (with transport pipes) I noticed a lot of the vanilla blocks in our spawn are now changed/displayed as craftory blocks.
![2021-10-13_14 25 41](https://user-images.githubusercontent.com/3696645/137132248-d1f20def-09c4-4f67-ab48-98f6c324a266.png)

**Comment by brettsaunders21** [comment]
> Also noticed that textures in the distance have more noise after installing the resource pack [imgur.com/a/oHfu2rG](https://imgur.com/a/oHfu2rG)
> 
> Mostly notice-able when looking at roads in the distance

I don't see how this can be us, all we do is add a resource pack that changes a few textures. It has no effect on Minecraft rendering or other texutres

**Comment by brettsaunders21** [comment]
Unfortunately the other issue is because we use mushroom stem block textures, we should only be using ones that Minecraft doesn't, but it seems we overrode a few others

Here is the list of block states we use
https://github.com/CraftoryStudios/Craftory-Tech/blob/master/resourcepacks/original/assets/minecraft/blockstates/mushroom_stem.json

If you use world edit to set all mushroom stems to one of the unused block states this will fix it

**Comment by cloakfox** [comment]
> Unfortunately the other issue is because we use mushroom stem block textures, we should only be using ones that Minecraft doesn't, but it seems we overrode a few others
> 
> Here is the list of block states we use https://github.com/CraftoryStudios/Craftory-Tech/blob/master/resourcepacks/original/assets/minecraft/blockstates/mushroom_stem.json
> 
> If you use world edit to set all mushroom stems to one of the unused block states this will fix it

Ah alright, i've fixed this issue now, thanks!
as for the resourcepack showing way more noise in the rendered image, that one doesnt make sense to me, it can easily be reproduced so not sure how nobody else has noticed it before.

**Comment by cloakfox** [comment]
> > Unfortunately the other issue is because we use mushroom stem block textures, we should only be using ones that Minecraft doesn't, but it seems we overrode a few others
> > Here is the list of block states we use https://github.com/CraftoryStudios/Craftory-Tech/blob/master/resourcepacks/original/assets/minecraft/blockstates/mushroom_stem.json
> > If you use world edit to set all mushroom stems to one of the unused block states this will fix it
> 
> Ah alright, i've fixed this issue now, thanks! as for the resourcepack showing way more noise in the rendered image, that one doesnt make sense to me, it can easily be reproduced so not sure how nobody else has noticed it before.

I noticed the noise is only applied when the player is not moving, when flying around or moving it's not applied.

**Comment by brettsaunders21** [comment]
We will look further into ensure we only use unused block stated in the future.

Regarding the other issue, we just add textures to a resource pack. It's very unlikely we cause this issue, I actually don't know how we could if we wanted to. 

No one is able to replicate it so it's likely to be an issue on your end, as it's rendering it would be a client side issue.
