### ISSUE TITLE
Gui Tiles

### ISSUE THREAD

**Issue by ErythroCraft** [CraftoryStudios/Craftory-Tech#158]
Gui tiles not in correct form.
Is your plugin **released or in alfa mode**?

All guis are not in correct forms. 
Watch out the example pictures how about.

![Screenshot 2021-11-01 081309](https://user-images.githubusercontent.com/76217862/139636614-14112192-1b23-423d-858c-993cd34cb359.png)
![Screenshot 2021-11-01 081522](https://user-images.githubusercontent.com/76217862/139636618-ffec6374-5021-42bb-b49f-d3e207c23eda.png)
![Screenshot 2021-11-01 081700](https://user-images.githubusercontent.com/76217862/139636619-abd8cc9f-69ce-4379-8217-80cfed6a4ad3.png)
![Screenshot 2021-11-01 081713](https://user-images.githubusercontent.com/76217862/139636620-1637bffe-5839-40df-aceb-935d09b35e6a.png)
![Screenshot 2021-11-01 081725](https://user-images.githubusercontent.com/76217862/139636623-0102fcdc-54e9-4c89-8ed2-0956073ffc51.png)

**Comment by ErythroCraft** [comment]
![Bild_2021-11-01_083009](https://user-images.githubusercontent.com/76217862/139636811-8e5c980d-a8b2-4193-937d-b2d13b76909c.png)

**Comment by brettsaunders21** [comment]
I believe the issue is that you have the "Force Unicode Font" option set to true on your local Minecraft client.

Please set this to false and let me know if this resolves the issue

**Comment by ErythroCraft** [comment]
I've seen yet.

I'll testing now.

**Comment by ErythroCraft** [comment]
So, I got a fix.

**Comment by ErythroCraft** [comment]
Please create a test version with the following update.

1. rename bar_0_b with the names of your real blocks.

- bar_0_b until bar_20_b
to the following results
+ bar_0_block_bracker until bar_20_block_bracker
+ bar_0_block_placer until bar_20_block_placer
+ bar_0_solar_panel until bar_20_solar_panel (for all solar panels)
+ bar_0_solid_fuel_generator until bar_20_solid_fuel_generator

The bar_0_t texture didn't show any results when I tested it.
bar_0_t until bar_20_t you can delete


2. I deleted all fonts in your texture pack and I've seen they have no results.
- So, you can delete all line in your plugin I markted red in the pictures
- This can give unicode fonts

![Bild_2021-11-08_024806](https://user-images.githubusercontent.com/76217862/140672016-1fc0e525-e922-4776-a186-f2326a901d12.png)


**If you have a test version, I'll create the textures and json files.**

**Comment by ErythroCraft** [comment]
[Comment: false]
